<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://www.mule.org/schema/mule/maven-v4_0_0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <groupId>dbede75e-6b29-4063-ac16-b9cad78a7cc4</groupId>
    <artifactId>worldtime-api</artifactId>
    <version>1.2.3</version>
    <packaging>mule-application</packaging>

    <name>worldtime-api</name>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <app.runtime>4.6.0</app.runtime>
        <mule.maven.plugin.version>3.8.2</mule.maven.plugin.version>
        <anypoint.platform.api.id>20819664</anypoint.platform.api.id>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>org.mule.tools.maven</groupId>
                <artifactId>mule-maven-plugin</artifactId>
                <version>${mule.maven.plugin.version}</version>
                <extensions>true</extensions>
                <configuration>
                    <classifier>mule-application</classifier>
                    <cloudhub2Deployment>
                        <uri>https://anypoint.mulesoft.com</uri>
                        <provider>MC</provider>
                        <environment>Sandbox</environment>
                        <target>Cloudhub-US-East-2</target>
                        <muleVersion>${app.runtime}</muleVersion>
                        <applicationName>satish-worldtime-api-ch2</applicationName>
                        <replicas>1</replicas>
                        <vCores>0.1</vCores>
                        <username>${anypoint.username}</username>
                        <password>${anypoint.password}</password>
                        <properties>
                            <anypoint.platform.api.id>${anypoint.platform.api.id}</anypoint.platform.api.id>
                        </properties>
                    </cloudhub2Deployment>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <distributionManagement>
        <repository>
            <id>anypoint-exchange-v3</id>
            <name>Corporate Repository</name>
            <url>https://maven.anypoint.mulesoft.com/api/v3/organizations/${project.groupId}/maven</url>
            <layout>default</layout>
        </repository>
    </distributionManagement>

    <repositories>
        <repository>
            <id>anypoint-exchange-v3</id>
            <url>https://maven.anypoint.mulesoft.com/api/v3/maven</url>
        </repository>
        <repository>
            <id>mulesoft-releases</id>
            <url>https://repository.mulesoft.org/releases/</url>
        </repository>
    </repositories>

    <pluginRepositories>
        <pluginRepository>
            <id>mulesoft-releases</id>
            <url>https://repository.mulesoft.org/releases/</url>
        </pluginRepository>
    </pluginRepositories>
</project>
